package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/lvdigitalpro/back/src/domain/entities"
)

// NewProject is the resolver for the newProject field.
func (r *mutationResolver) NewProject(ctx context.Context, input entities.InputNewProject) (string, error) {
	panic(fmt.Errorf("not implemented: NewProject - newProject"))
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input entities.InputUpdateProject) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateProject - updateProject"))
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, input entities.InputDeleteProject) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteProject - deleteProject"))
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*entities.Project, error) {
	panic(fmt.Errorf("not implemented: Projects - projects"))
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*entities.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}
