package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/lvdigitalpro/back/src/domain/entities"
)

// NewProject is the resolver for the newProject field.
func (r *mutationResolver) NewProject(ctx context.Context, input entities.InputNewProject) (string, error) {

	exec, err := r.ProjectService.NewProject(ctx, input)

	if err != nil {
		return "", err
	}

	return *exec, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input entities.InputUpdateProject) (string, error) {

	exec, err := r.ProjectService.UpdateProject(ctx, input)

	if err != nil {
		return "", err
	}

	return *exec, nil

}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, input entities.InputDeleteProject) (string, error) {

	exec, err := r.ProjectService.DeleteProject(ctx, input)

	if err != nil {
		return "", err
	}

	return *exec, nil
}

// GetProjects is the resolver for the getProjects field.
func (r *queryResolver) GetProjects(ctx context.Context) ([]*entities.Project, error) {

	projects, err := r.ProjectService.GetProjects(ctx)

	if err != nil {
		return nil, err
	}

	return projects, nil
}

// GetProject is the resolver for the getProject field.
func (r *queryResolver) GetProject(ctx context.Context, codProject int) (*entities.Project, error) {

	project, err := r.ProjectService.GetProject(ctx, codProject)

	if err != nil {
		return nil, err
	}

	return project, nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
