package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"github.com/lvdigitalpro/back/src/domain/entities"
	"github.com/lvdigitalpro/back/src/graph"
)

// NewUser is the resolver for the newUser field.
func (r *mutationResolver) NewUser(
	ctx context.Context, role entities.Role, name string, lastname string, ir string, email string, password string,
	passwordConfirmation string, enterpriseName *string, nrle *string,
) (string, error) {
	exec, err := r.UserService.NewUser(
		ctx, role, name, lastname, ir, email, password,
		passwordConfirmation,
		enterpriseName, nrle,
	)

	if err != nil {
		return "", err
	}

	return *exec, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(
	ctx context.Context, id string, name *string, lastname *string, ir *string, email *string, password *string,
	passwordConfirmation *string, enterpriseName *string, nrle *string,
) (string, error) {
	exec, err := r.UserService.UpdateUser(
		ctx, id, *name, *lastname, *ir, *email, *password, *passwordConfirmation,
		enterpriseName, nrle,
	)

	if err != nil {
		return "", err
	}

	return *exec, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(
	ctx context.Context, id string, ir string, nrle *string, password string, passwordConfirmation string,
) (string, error) {
	exec, err := r.UserService.DeleteUser(
		ctx, id, ir, nrle, password, passwordConfirmation,
	)

	if err != nil {
		return "", err
	}

	return *exec, nil
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*entities.User, error) {
	exec, err := r.UserService.GetUsers(ctx)

	if err != nil {
		return nil, err
	}

	return exec, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*entities.User, error) {
	exec, err := r.UserService.GetUser(ctx, id)

	if err != nil {
		return nil, err
	}

	return exec, nil
}

// GetUserByEmail is the resolver for the getUserByEmail field.
func (r *queryResolver) GetUserByEmail(ctx context.Context, email string) (*entities.User, error) {
	exec, err := r.UserService.GetUserByEmail(ctx, email)

	if err != nil {
		return nil, err
	}

	return exec, nil
}

// GetUserByIr is the resolver for the getUserByIR field.
func (r *queryResolver) GetUserByIr(ctx context.Context, ir string) (*entities.User, error) {
	exec, err := r.UserService.GetUserByIr(ctx, ir)

	if err != nil {
		return nil, err
	}

	return exec, nil
}

// GetUserByProject is the resolver for the getUserByProject field.
func (r *queryResolver) GetUserByProject(ctx context.Context, project string) (*entities.User, error) {

	exec, err := r.UserService.GetUserByProject(ctx, project)

	if err != nil {
		return nil, err
	}

	return exec, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
